export const locationData = {
  a1: [
    "Gopal pura bypass, Jaipur",
    "Mahesh Nagar, Jaipur",
    " Tonk Phatak, Jaipur",
    "C Scheme, Jaipur",
    " Chaura Rasta, Jaipur",
    " Chomu House, Jaipur",
    " Chitrakoot Vaishali Nagar, Jaipur",
    " Bapu Nagar, Jaipur",
    " Civil Lines, Jaipur",
    "Barkat Nagar, Jaipur",
  ],
  a2: [
    " VKI Areas, Jaipur",
    "Siker Road, Jaipur",
    "Ajmeri Gate, Jaipur",
    "Akshaya patra Temple, Jaipur",
    "Bani Park,Jaipur",
    "Bajaj Nagar, Jaipur",
    "Brahmpuri, Jaipur",
    "Chandpole Bazar, Jaipur",
    " Malviya Nagar, Jaipur",
    " Sodala, Jaipur",
  ],
  a3: [
    "Partap Nagar,Jaipur",
    " Jagatpura, Jaipur",
    "Sanganer, Jaipur",
    "Sitapura, Jaipur",
    "Mansarovar, Jaipur",
    "Lal Kothi, Jaipur",
    "Adarsh Nagar, Jaipur",
    "Ambabari, Jaipur",
    " Mansarovar, Jaipur",
    "Vaishali Nagar, Jaipur",
  ],
};
